encryptionsalt: v1:JDVXG0inRtQ=:v1:gcRj2GkSXOtq4n6w:VCq7Emqf00ybfpTlhkDoBVUzzaSuUA==
config:
  arch-review:namespace: arch-review-dev
  arch-review:app_name: arch-review-api
  arch-review:app_port: "8000"
  arch-review:image: arch-review-image:dev
  arch-review:replicas: "1"
  arch-review:ingress_host: arch-review.local
  arch-review:install_traefik: "true"
  arch-review:traefik_name: traefik
  arch-review:traefik_namespace: traefik
  arch-review:traefik_http_node_port: "30080"
  arch-review:traefik_https_node_port: "30443"
  arch-review:traefik_ingress_class: traefik
  arch-review:frontend_name: arch-review-frontend
  arch-review:frontend_port: "3000"
  arch-review:frontend_image: arch-review-frontend-image:dev
  arch-review:frontend_replicas: "1"
  arch-review:pgvector_name: pgvector
  arch-review:pgvector_port: "5432"
  arch-review:pgvector_image: pgvector/pgvector:pg16
  arch-review:pgvector_db: arch_review
  arch-review:pgvector_user: arch_review
  arch-review:pgvector_storage_size: 256Mi
  arch-review:neo4j_name: neo4j
  arch-review:neo4j_http_port: "7474"
  arch-review:neo4j_bolt_port: "7687"
  arch-review:neo4j_image: neo4j:5-community
  arch-review:neo4j_user: neo4j
  arch-review:neo4j_storage_size: 256Mi
  arch-review:tempo_name: tempo
  arch-review:tempo_image: grafana/tempo:latest
  arch-review:tempo_http_port: "3200"
  arch-review:tempo_otlp_grpc_port: "4317"
  arch-review:tempo_otlp_http_port: "4318"
  arch-review:loki_name: loki
  arch-review:loki_image: grafana/loki:latest
  arch-review:loki_port: "3100"
  arch-review:prometheus_name: prometheus
  arch-review:prometheus_image: prom/prometheus:latest
  arch-review:prometheus_port: "9090"
  arch-review:grafana_name: grafana
  arch-review:grafana_image: grafana/grafana:latest
  arch-review:grafana_port: "3000"
  arch-review:grafana_host: grafana.arch-review.local
