from collections.abc import Sequence
from typing import Protocol

from app.intake.domain.entities.document import Document
from app.intake.domain.value_objects.status import ProcessingStatus


class DocumentRepository(Protocol):
    async def save(self, document: Document) -> None: ...
    async def find_by_id(self, document_id: str) -> Document | None: ...
    async def find_by_status(self, status: ProcessingStatus) -> Sequence[Document]: ...
    async def delete(self, document_id: str) -> None: ...
